openapi: 3.0.0
info:
  title: World Modelers Federated Search API
  description: |
    A federated search API that negotiates queries across Datamarts and the UAZ 
    concept mapping service on behalf of SuperMaaS and CauseMos.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server for testing federated search

paths:
  /search:
    post:
      tags:
      - Search
      summary: Search over Datamarts
      description: |
        Search over Datamarts in order to find datasets and variables of interest.
      requestBody:
        description: |
          Search query definition. Must provide `data_location` and _should_ provide 
          at least one a `[geo, temporal, keyword]` filter.
        required: true
        content:
          application/json:
            schema:
              anyOf:
                - $ref: '#/components/schemas/geospatial_search'
                - $ref: '#/components/schemas/temporal_search'
                - $ref: '#/components/schemas/keyword_search'            
              oneOf:
                - $ref: '#/components/schemas/data_location'
            example: 
              data_location: ISI
              keywords: 
                [wfp, world food prices]
              time: 
                {start: "2018-01-01 00:00:00",
                 end: "2020-08-31 00:00:00"}
              geo: 
                {latitude1: 48.5, 
                 longitude1: -123.1, 
                 latitude2: 48.2, 
                 longitude2: -122.5}
      responses:
        200:
          description: "SUCCESS"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/search_result'
                
  /search_concepts/{concept_name}:
    get:
      tags:
      - Search
      summary: Concept based search
      description: |
        Search based on concepts from the [World Modelers Ontology](https://github.com/worldmodelers/ontologies)
      parameters:
        - in: path
          name: concept_name
          schema:
            type: string
          required: true
          description: World Modelers ontology concept
      responses:
        200:
          description: "SUCCESS"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/search_result'

  /metadata/{data_location}/{id}:
    get:
      tags:
      - Metadata
      summary: Obtain variabile/dataset metadata
      description: Obtain metadata for specified datamart and dataset/variable ID
      parameters:
        - in: path
          name: data_location
          schema:
            type: string
          required: true
          description: datamart from which data is downloaded
        - in: path  
          name: id
          schema:
            type: string
          required: true
          description: dataset_id (NYU) or variable_id (ISI)
          
      responses:
        200:
          description: "SUCCESS"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/metadata_result'  
                

  /download/{data_location}/{id}:
    get:
      tags:
      - Download
      summary: Download datasets
      description: Download a full dataset by its ID
      operationId: download_id
      parameters:
      - in: path
        name: data_location
        schema:
          type: string
        required: true
        example: NYU
      - in: path
        name: id
        description: dataset_id of dataset
        schema:
          type: string
        required: true
        example: "NYU-123123123123123"
      responses:
        '200':
          description: "Return a csv file"
          content:
            text/csv:
              schema:
                type: string
                format: binary            

components:
  schemas:
    search_result:
      type: array
      items:
        type: object
        properties:
          data_location:
            type: string
            description: The location of the data (e.g. a Datamart)
            example: NYU
          id:
            type: string
            description: The id of the dataset or variable within the data location
            example: "NYU-123123123123123"
          score: 
            type: number
            description: |
              Ranking of the dataset or variable based on its 
              proximity to the search of interest.
            example: 0.92
        required:
        - data_location
        - id
        - score      
        
    data_location:
      type: object
      description: The location of the data
      properties:
        data_location:
          type: string
          enum:
            - ISI
            - NYU
            - All
          default: All
          example: ISI
      required: 
      - datamart
  
    temporal_search:
      type: object
      description: Describes columns containing temporal information.
      properties:
        time:
          type: object
          properties:
            start:
              type: string
              description: Dates-of-interest are more recent than this date
              example: "2018-01-01 00:00:00"
            end:
              type: string
              description: Dates-of-interest are older than this date
              example: "2020-08-31 23:00:00"
          required:
          - start
          - end
      
    geospatial_search:
        type: object
        description: Describes columns containing geospatial entities. West and South are negative.
        properties:
          geo:
            type: object
            properties:
              latitude1:
                type: number
                description: The latitude of the top left point.
                example: 14.5
              longitude1:
                type: number
                description: The longitude of the top left point.
                example: 3.0
              latitude2:
                type: number
                description: The latitude of the bottom right point.
                example: 32.6
              longitude2:
                type: number
                description: The longitude of the bottom right point.
                example: 46.8
            required:
            - latitude1
            - longitude1
            - latitude2
            - longitude2
        
    keyword_search:
      type: object
      description: Text based search  
      properties:
        keywords:
          type: object
          properties:
            keywords:
              type: array
              items:
                type: string
              example: [wfp, world food price]
          required:
          - keywords

    metadata_result:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
            description: Name of the Dataset
            example: WFP Prices Eth
          description:
            type: string
            example: World Food Program prices for Ethiopia
          dataset_id:
            type: string
            description: The id of the dataset or variable within the data location
            example: ISI_wfp_maize            
          url:
            type: string
            example: http://wfp.com/prices
          source:
            type: string
            example: World Food Program
        required: 
        - name
        - description