openapi: 3.0.0
info:
  title: World Modelers Federated Search API
  description: "A federated search API that negotiates queries across Datamarts and\
    \ the UAZ \nconcept mapping service on behalf of SuperMaaS and CauseMos.\n"
  version: 1.0.1
servers:
- url: http://localhost:8080
  description: Local server for testing federated search
paths:
  /search:
    post:
      tags:
      - Search
      summary: Search over Datamarts
      description: |
        Search over Datamarts to find datasets and variables of interest.
      operationId: search_post
      requestBody:
        description: "Search query definition. _Must_ provide `data_location` and\
          \ _at least_ one of `[geo, temporal, keywords]` filter.<br> \nNYU Options:\
          \ One, or combo of [geo, temporal, keywords]<br>\nISI Option: [Keywords]\
          \ \n"
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body'
            example:
              data_location: NYU
              keywords:
              - wfp
              - world food prices
              time:
                start: 2010-01-01 00:00:00
                end: 2020-08-31 00:00:00
              geo:
                type: bbox
                value:
                  bbox:
                    latitude1: 16.0
                    longitude1: 33
                    latitude2: 2
                    longitude2: 49.5
        required: true
      responses:
        "200":
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/search_result'
      x-openapi-router-controller: swagger_server.controllers.search_controller
  /search_concepts/{concept_name}:
    get:
      tags:
      - Search
      summary: Concept based search
      description: |
        Search based on concepts from the [World Modelers Ontology](https://github.com/worldmodelers/ontologies)
      operationId: search_concepts_concept_name_get
      parameters:
      - name: concept_name
        in: path
        description: World Modelers ontology concept
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/search_result'
      x-openapi-router-controller: swagger_server.controllers.search_controller
  /metadata/{data_location}/{dataset_id}:
    get:
      tags:
      - Metadata
      summary: Obtain metadata for ISI/NYU datasets
      description: |
        Obtain metadata for specified datamart and dataset ID
      operationId: metadata_data_location_dataset_id_get
      parameters:
      - name: data_location
        in: path
        description: Select Datamart
        required: true
        style: simple
        explode: false
        schema:
          type: string
          enum:
          - NYU
          - ISI
      - name: dataset_id
        in: path
        description: Enter dataset_id
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: variable_id
        in: query
        description: "*ISI Only*: variable_id or leave blank"
        required: false
        style: form
        explode: true
        schema:
          type: string 
      responses:
        "200":
          description: SUCCESS
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/metadata_result_meta'
      x-openapi-router-controller: swagger_server.controllers.metadata_controller
  /download_variables/{data_location}/{dataset_id}:
    post:
      tags:
      - Download
      summary: Download ISI variables
      description: |
        ISI ONLY: Download variables into single file from an ISI dataset
      operationId: download_variables_data_location_dataset_id_post
      parameters:
      - name: data_location
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          enum:
          - ISI
        example: ISI
      - name: dataset_id
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          default: None
        example: WDI
      requestBody:
        description: |
          Enter the ISI variable_IDs you would like to download. At least one is required.
        content:
          application/json:
            schema:
              type: array
              items:
                type: string
            example:
            - access_to_electricity_of_population
            - access_to_clean_fuels_and_technologies_for_cooking_of_population
        required: true
      responses:
        "200":
          description: Return a csv file
          content:
            text/csv:
              schema:
                type: string
                format: binary
                x-content-type: text/csv
      x-openapi-router-controller: swagger_server.controllers.download_controller
  /download/{data_location}/{dataset_id}:
    get:
      tags:
      - Download
      summary: Download NYU datasets
      description: 'NYU ONLY: Download dataset by its daataset_id'
      operationId: download_data_location_dataset_id_get
      parameters:
      - name: data_location
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
          enum:
          - NYU
        example: NYU
      - name: dataset_id
        in: path
        description: dataset_id of dataset
        required: true
        style: simple
        explode: false
        schema:
          type: string
        example: NYU-123123123
      responses:
        "200":
          description: Return a csv file
          content:
            text/csv:
              schema:
                type: string
                format: binary
                x-content-type: text/csv
      x-openapi-router-controller: swagger_server.controllers.download_controller
components:
  schemas:
    search_result:
      required:
      - data_location
      - dataset_id
      - name
      - score
      type: object
      properties:
        data_location:
          type: string
          description: The location of the data (e.g. a Datamart)
          example: NYU
        dataset_id:
          type: string
          description: The id of the dataset or variable within the data location
          example: NYU-123123123123123
        variable_id:
          type: string
          description: The id of the variable
          example: VUAZ-8346
        name:
          type: string
          example: WFP dataset
        description:
          type: string
          example: Food prices for Ethiopia
        score:
          type: number
          description: "Ranking of the dataset or variable based on its \nproximity\
            \ to the search of interest.\n"
          example: 0.92
      example:
        score: 0.92
        variable_id: VUAZ-8346
        dataset_id: NYU-123123123123123
        name: WFP dataset
        description: Food prices for Ethiopia
        data_location: NYU
    data_location:
      required:
      - data_location
      type: object
      properties:
        data_location:
          type: string
          example: NYU
          default: All
          enum:
          - ISI
          - NYU
          - All
      description: The location of the data
    temporal_search:
      type: object
      properties:
        time:
          $ref: '#/components/schemas/temporal_search_time'
      description: Describes columns containing temporal information.
    geospatial_search:
      required:
      - type
      - value
      type: object
      properties:
        type:
          type: string
          description: either bbox or place
          enum:
          - place
          - bbox
        value:
          $ref: '#/components/schemas/geospatial_search_value'
      description: Describes columns containing geospatial entities. West and South
        are negative.
    keyword_search:
      type: object
      properties:
        keywords:
          $ref: '#/components/schemas/keyword_search_keywords'
      description: Text based search
    metadata_result:
      required:
      - description
      - name
      type: object
      properties:
        name:
          type: string
          description: Name of the Dataset
          example: WFP Prices Eth
        description:
          type: string
          example: World Food Program prices for Ethiopia
        dataset_id:
          type: string
          description: The id of the dataset or variable within the data location
          example: ISI_wfp_maize
        variable_id:
          type: string
          description: The variable id searched for
          example: ISI_wfp_maize
        url:
          type: string
          example: http://wfp.com/prices
        source:
          type: string
          example: World Food Program
        spatial_resolution:
          type: string
          example: country
        temporal_resolution:
          type: string
          example: year
        z_meta:
          type: array
          example:
          - all meta here
          items:
            type: object
      example:
        z_meta:
        - all meta here
        dataset_id: ISI_wfp_maize
        name: WFP Prices Eth
        description: World Food Program prices for Ethiopia
        source: World Food Program
        temporal_resolution: year
        url: http://wfp.com/prices
        spatial_resolution: country
    metadata_result_meta:
      type: array
      items:
        $ref: '#/components/schemas/metadata_result'
    body:
      anyOf:
      - $ref: '#/components/schemas/geospatial_search'
      - $ref: '#/components/schemas/temporal_search'
      - $ref: '#/components/schemas/keyword_search'
      oneOf:
      - $ref: '#/components/schemas/data_location'
    temporal_search_time:
      required:
      - end
      - start
      type: object
      properties:
        start:
          type: string
          description: Dates-of-interest are more recent than this date
          example: 2018-01-01 00:00:00
        end:
          type: string
          description: Dates-of-interest are older than this date
          example: 2020-08-31 23:00:00
    geospatial_search_value_bbox:
      required:
      - latitude1
      - latitude2
      - longitude1
      - longitude2
      type: object
      properties:
        latitude1:
          type: number
          description: The latitude of the top left point.
          example: 14.9
        longitude1:
          type: number
          description: The longitude of the top left point.
          example: 3
        latitude2:
          type: number
          description: The latitude of the bottom right point.
          example: 32.6
        longitude2:
          type: number
          description: The longitude of the bottom right point.
          example: 46.8
    geospatial_search_value_place:
      required:
      - area_name
      type: object
      properties:
        area_name:
          type: array
          example: Ethiopia
          items:
            type: string
      description: list of names/places to search
    geospatial_search_value:
      properties:
        bbox:
          $ref: '#/components/schemas/geospatial_search_value_bbox'
        place:
          $ref: '#/components/schemas/geospatial_search_value_place'
    keyword_search_keywords:
      required:
      - keywords
      type: object
      properties:
        keywords:
          type: array
          example:
          - wfp
          - world food price
          items:
            type: string

