# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.geospatial_search_value_bbox import GeospatialSearchValueBbox  # noqa: F401,E501
from swagger_server.models.geospatial_search_value_place import GeospatialSearchValuePlace  # noqa: F401,E501
from swagger_server import util


class GeospatialSearchValue(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, bbox: GeospatialSearchValueBbox=None, place: GeospatialSearchValuePlace=None):  # noqa: E501
        """GeospatialSearchValue - a model defined in Swagger

        :param bbox: The bbox of this GeospatialSearchValue.  # noqa: E501
        :type bbox: GeospatialSearchValueBbox
        :param place: The place of this GeospatialSearchValue.  # noqa: E501
        :type place: GeospatialSearchValuePlace
        """
        self.swagger_types = {
            'bbox': GeospatialSearchValueBbox,
            'place': GeospatialSearchValuePlace
        }

        self.attribute_map = {
            'bbox': 'bbox',
            'place': 'place'
        }
        self._bbox = bbox
        self._place = place

    @classmethod
    def from_dict(cls, dikt) -> 'GeospatialSearchValue':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The geospatial_search_value of this GeospatialSearchValue.  # noqa: E501
        :rtype: GeospatialSearchValue
        """
        return util.deserialize_model(dikt, cls)

    @property
    def bbox(self) -> GeospatialSearchValueBbox:
        """Gets the bbox of this GeospatialSearchValue.


        :return: The bbox of this GeospatialSearchValue.
        :rtype: GeospatialSearchValueBbox
        """
        return self._bbox

    @bbox.setter
    def bbox(self, bbox: GeospatialSearchValueBbox):
        """Sets the bbox of this GeospatialSearchValue.


        :param bbox: The bbox of this GeospatialSearchValue.
        :type bbox: GeospatialSearchValueBbox
        """

        self._bbox = bbox

    @property
    def place(self) -> GeospatialSearchValuePlace:
        """Gets the place of this GeospatialSearchValue.


        :return: The place of this GeospatialSearchValue.
        :rtype: GeospatialSearchValuePlace
        """
        return self._place

    @place.setter
    def place(self, place: GeospatialSearchValuePlace):
        """Sets the place of this GeospatialSearchValue.


        :param place: The place of this GeospatialSearchValue.
        :type place: GeospatialSearchValuePlace
        """

        self._place = place
