# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.geospatial_search_value import GeospatialSearchValue  # noqa: F401,E501
from swagger_server import util


class GeospatialSearch(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, type: str=None, value: GeospatialSearchValue=None):  # noqa: E501
        """GeospatialSearch - a model defined in Swagger

        :param type: The type of this GeospatialSearch.  # noqa: E501
        :type type: str
        :param value: The value of this GeospatialSearch.  # noqa: E501
        :type value: GeospatialSearchValue
        """
        self.swagger_types = {
            'type': str,
            'value': GeospatialSearchValue
        }

        self.attribute_map = {
            'type': 'type',
            'value': 'value'
        }
        self._type = type
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'GeospatialSearch':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The geospatial_search of this GeospatialSearch.  # noqa: E501
        :rtype: GeospatialSearch
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this GeospatialSearch.

        either bbox or place  # noqa: E501

        :return: The type of this GeospatialSearch.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this GeospatialSearch.

        either bbox or place  # noqa: E501

        :param type: The type of this GeospatialSearch.
        :type type: str
        """
        allowed_values = ["place", "bbox"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def value(self) -> GeospatialSearchValue:
        """Gets the value of this GeospatialSearch.


        :return: The value of this GeospatialSearch.
        :rtype: GeospatialSearchValue
        """
        return self._value

    @value.setter
    def value(self, value: GeospatialSearchValue):
        """Sets the value of this GeospatialSearch.


        :param value: The value of this GeospatialSearch.
        :type value: GeospatialSearchValue
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value
